---
on:
  - push

jobs:
  terraform:
    name: terraform
    env:
      # These variables are for the terraform vault provider.
      VAULT_ADDR: "http://vault:8200"
      VAULT_TOKEN: "simple"
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: default
      max-parallel: 3
    services:
      vault:
        image: vault
        env:
          VAULT_DEV_ROOT_TOKEN_ID: "simple"
        ports:
          - 8200:8201
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform init
        uses: robertdebock/terraform-action@1.1.2
        with:
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform validate
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: validate
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform plan
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: plan
          directory: ./examples/${{ matrix.config.name }}
      - name: terraform apply
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: apply
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
      - name: terraform destroy
        uses: robertdebock/terraform-action@1.1.2
        with:
          action: destroy
          directory: ./examples/${{ matrix.config.name }}
        env:
          TF_CLI_ARGS: "-input=false -auto-approve"
        if: ${{ always() }}
